version: "3"

services:


    app:
        restart: always
        build:
            context: .
        expose:
            - 8000
        volumes:
            - ./app:/app
        command: >
            sh -c """python manage.py wait_for_db &&
                     python manage.py migrate &&
                     gunicorn app.wsgi:application -w 2 -b :8000 --reload
                """
        environment:
            - SQL_ENGINE=django.db.backends.postgresql_psycopg2
            - SQL_DATABASE=app
            - SQL_USER=postgres
            - SQL_PASSWORD=helloworld
            - SQL_HOST=db
            - SQL_PORT=5432
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: NGINXDOCKERNAME3
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - ./config/nginx:/etc/nginx/conf.d
            - ./static:/static
            - ./media:/media
        depends_on:
            - app

    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=helloworld


volumes:
    static_volume:
    postgres_data: